---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_4f196822b589:latest
          env:
            - name: REACT_APP_SHARE_KAKAO_LINK_KEY
              valueFrom:
                secretKeyRef:
                  name: front-kakao
                  key: kakao-link-key
            - name: REACT_APP_BACKEND_DEPLOY
              valueFrom:
                secretKeyRef:
                  name: front-kakao
                  key: backend-deploy
            - name: GENERATE_SOURCEMAP
              valueFrom:
                secretKeyRef:
                  name: front-env
                  key: generate-source
            - name: REACT_APP_FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: front-env
                  key: fb-api-key
            - name: REACT_APP_FIREBASE_AUTH_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: front-env
                  key: fb-auth-domain
            - name: REACT_APP_FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: front-env
                  key: fb-project-id
            - name: REACT_APP_FIREBASE_STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: front-env
                  key: fb-bucket
            - name: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
              valueFrom:
                secretKeyRef:
                  name: front-env
                  key: fb-sender
            - name: REACT_APP_FIREBASE_APP_ID
              valueFrom:
                secretKeyRef:
                  name: front-env
                  key: fb-app-id
            - name: REACT_APP_FIREBASE_MEASUREMENT_ID
              valueFrom:
                secretKeyRef:
                  name: front-env
                  key: fb-measure
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
